model:
  base_learning_rate: 1.0e-4 
  target: ldm.models.diffusion.ddpm_dyga.LatentDiffusion
  params:
    linear_start: 0.0015
    linear_end: 0.0155
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    loss_type: l1
    first_stage_key: "image"
    cond_stage_key: "image"
    image_size: 16
    channels: 3
    cond_stage_trainable: true
    concat_mode: False
    scale_by_std: True
    conditioning_key: adm
    monitor: 'train/epoch_num'

    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel_skip-dropout.UNetModel
      params:
        image_size: 16
        in_channels: 3
        out_channels: 3
        model_channels: 64
        attention_resolutions: [ 1, 2, 4]
        num_res_blocks: 2
        channel_mult: [ 1,2,4,4 ]
        num_heads: 8
        use_scale_shift_norm: true
        resblock_updown: true
        context_dim: 32
        use_spatial_transformer: true
        dropout: 0.1
        skip_dropout: 0.2

    first_stage_config:
      target: ldm.models.autoencoder.VQModelInterface
      params:
        embed_dim: 3
        n_embed: 2048
        monitor: "val/rec_loss"
        ckpt_path: "your/path"
        ddconfig:
          double_z: false
          z_channels: 3
          resolution: 64
          in_channels: 3
          out_ch: 3
          ch: 32
          ch_mult:       
          - 1
          - 2
          - 4          
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity

    cond_stage_config:
      target: ldm.modules.encoders.modules.FeatureExtractor
      params:
        latent_units: 20
        d: 64
        image_size: 64
        num_channels: 3
        context_dim: 32

    HDDC_config:
      target: ldm.modules.gaussian.DyGA.DyGA
      params:
        n_clusters: 8
        max_clusters: 32
        max_iter: 30
        tol: 1e-4
        batch_size: 103600
        
data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 512
    wrap: True
    num_workers: 8
    train:
      target: ldm.data.dis.Cars3DTrain
    validation:
      target: ldm.data.dis.Cars3DTrain
    test:
      target: ldm.data.dis.Cars3DTrain

lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 10000
        max_images: 16
        increase_log_steps: false
        log_images_kwargs:
          inpaint: false
          plot_diffusion_rows: false
          plot_progressive_rows: false
          plot_swapped_concepts: true
          plot_decoded_xstart: false
  trainer:
    benchmark: True